In [85]:
#series

In [86]:
import pandas as pd

In [87]:
s = pd.Series([23,34,56,78,10])

In [88]:
s

0    23
1    34
2    56
3    78
4    10
dtype: int64

In [89]:
s1 = pd.Series([23,34,56,78,10,'pcp'])

In [90]:
s1

0     23
1     34
2     56
3     78
4     10
5    pcp
dtype: object

In [91]:
s1[3]

78

In [92]:
s1[3] =100

In [93]:
s1

0     23
1     34
2     56
3    100
4     10
5    pcp
dtype: object

# DataFrame

In [94]:
roll = pd.Series([1,2,3,4,5])
name = pd.Series(['ankit','riya','geet','pratik','ravindra'])
marks= pd.Series([56,69,71,82,89])

In [95]:
df = pd.DataFrame({
    'roll': roll,
    'name': name,
    'marks':marks,
})
df

   roll      name  marks
0     1     ankit     56
1     2      riya     69
2     3      geet     71
3     4    pratik     82
4     5  ravindra     89

In [96]:
df.shape

(5, 3)

In [97]:
df.size

15

In [98]:
df.columns

Index(['roll', 'name', 'marks'], dtype='object')

In [99]:
#check your folder?
import os
os.getcwd()

'C:\\Users\\Lenovo'

In [100]:
df = pd.read_csv("student.csv")

In [101]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [102]:
df = pd.read_csv("student1.csv")

In [103]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [104]:
df = pd.read_csv("student1.csv")
df;

In [105]:
headers =['a','b','c','d','e']

In [106]:
df=pd.read_csv("student1.csv",names=headers)
df

    a        b   c      d   e
0   1     anil  TE  56.77  22
1   2     amit  TE  59.77  21
2   3   aniket  BE  76.88  19
3   4  ajinkya  TE  69.66  20
4   5     asha  TE  63.28  20
5   6   ayesha  BE  49.55  20
6   7     amar  BE  65.34  19
7   8    amita  BE  68.33  23
8   9     amol  TE  56.75  20
9  10    anmol  BE  78.66  21

In [107]:
# student3.tsv

In [108]:
df = pd.read_csv('student3.tsv',sep = '\t')
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [109]:
df=pd.read_csv('student.csv')
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [110]:
df.shape

(10, 5)

In [111]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [113]:
df.describe()

           roll      marks        age
count  10.00000  10.000000  10.000000
mean    5.50000  64.499000  20.500000
std     3.02765   9.207179   1.269296
min     1.00000  49.550000  19.000000
25%     3.25000  57.520000  20.000000
50%     5.50000  64.310000  20.000000
75%     7.75000  69.327500  21.000000
max    10.00000  78.660000  23.000000

In [114]:
df.head()

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [115]:
df.head(3)

   roll    name class  marks  age
0     1    anil    TE  56.77   22
1     2    amit    TE  59.77   21
2     3  aniket    BE  76.88   19

In [116]:
df.tail()

   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [117]:
df.tail(3)

   roll   name class  marks  age
7     8  amita    BE  68.33   23
8     9   amol    TE  56.75   20
9    10  anmol    BE  78.66   21

# data slicing

In [119]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [121]:
df.iloc[2:5,1:4]

      name class  marks
2   aniket    BE  76.88
3  ajinkya    TE  69.66
4     asha    TE  63.28

In [124]:
df.iloc[[2,3,5],0:4]

   roll     name class  marks
2     3   aniket    BE  76.88
3     4  ajinkya    TE  69.66
5     6   ayesha    BE  49.55

In [127]:
df.iloc[[2,3,5],[0,1,3]]

   roll     name  marks
2     3   aniket  76.88
3     4  ajinkya  69.66
5     6   ayesha  49.55

In [128]:
df.iloc[:,1]

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [129]:
df.iloc[1,1]

'amit'

In [130]:
# loc

In [131]:
df.loc[:,"name"]

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [134]:
df.loc[:,['name','class']]

      name class
0     anil    TE
1     amit    TE
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5   ayesha    BE
6     amar    BE
7    amita    BE
8     amol    TE
9    anmol    BE

In [135]:
df[['name','marks']]

      name  marks
0     anil  56.77
1     amit  59.77
2   aniket  76.88
3  ajinkya  69.66
4     asha  63.28
5   ayesha  49.55
6     amar  65.34
7    amita  68.33
8     amol  56.75
9    anmol  78.66

In [136]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [137]:
df.drop(4)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [142]:
df.drop([5,6,7])

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [143]:
df.drop('class',axis=1)

   roll     name  marks  age
0     1     anil  56.77   22
1     2     amit  59.77   21
2     3   aniket  76.88   19
3     4  ajinkya  69.66   20
4     5     asha  63.28   20
5     6   ayesha  49.55   20
6     7     amar  65.34   19
7     8    amita  68.33   23
8     9     amol  56.75   20
9    10    anmol  78.66   21

In [147]:
df.drop(['class','marks'],axis=1)

   roll     name  age
0     1     anil   22
1     2     amit   21
2     3   aniket   19
3     4  ajinkya   20
4     5     asha   20
5     6   ayesha   20
6     7     amar   19
7     8    amita   23
8     9     amol   20
9    10    anmol   21

In [148]:
# mean

In [149]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [153]:
df['marks'].max()

78.66

In [154]:
df['class'].mode()

0    BE
1    TE
Name: class, dtype: object

In [155]:
df['marks'].min()

49.55

In [156]:
df['name'].str.upper()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5     AYESHA
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [157]:
df['name'].str.startswith('an')

0     True
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: name, dtype: bool

In [158]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [159]:
# add 0r modify columns

In [162]:
df['roll']=df['roll']+100

In [163]:
df

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106   ayesha    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [164]:
gender=['m','m','m','m','f','f','m','f','m','m']

In [165]:
df['gender']=gender

In [166]:
df

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      m
1   102     amit    TE  59.77   21      m
2   103   aniket    BE  76.88   19      m
3   104  ajinkya    TE  69.66   20      m
4   105     asha    TE  63.28   20      f
5   106   ayesha    BE  49.55   20      f
6   107     amar    BE  65.34   19      m
7   108    amita    BE  68.33   23      f
8   109     amol    TE  56.75   20      m
9   110    anmol    BE  78.66   21      m

In [167]:
df['gender'].value_counts()

gender
m    7
f    3
Name: count, dtype: int64

In [168]:
df['marks']>60

0    False
1    False
2     True
3     True
4     True
5    False
6     True
7     True
8    False
9     True
Name: marks, dtype: bool

In [169]:
df[df['marks']>60]

   roll     name class  marks  age gender
2   103   aniket    BE  76.88   19      m
3   104  ajinkya    TE  69.66   20      m
4   105     asha    TE  63.28   20      f
6   107     amar    BE  65.34   19      m
7   108    amita    BE  68.33   23      f
9   110    anmol    BE  78.66   21      m

In [170]:
df[(df['marks']>60)&(df['class']=="BE")]

   roll    name class  marks  age gender
2   103  aniket    BE  76.88   19      m
6   107    amar    BE  65.34   19      m
7   108   amita    BE  68.33   23      f
9   110   anmol    BE  78.66   21      m

In [178]:
x = df[(df['marks']>60)&(df['class']=="BE")]

In [179]:
x.to_csv('output.csv',index=False)