In [2]:
# student3.csv

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('student3.csv')
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [5]:
df['name']

0        anil
1        amit
2      aniket
3     ajinkya
4        asha
5      ayesha
6        amar
7       Amita
8        amol
9        amol
10      anmol
11     surbhi
12      Sujay
13    subhash
14     sachin
15    shalini
Name: name, dtype: object

In [6]:
df['name']=df['name'].str.title()

In [7]:
df

    roll     name class  marks    age
0      1     Anil    TE   56.77  22.0
1      2     Amit    TE   59.77  21.0
2      3   Aniket    BE   76.88  19.0
3      4  Ajinkya    TE   69.66  20.0
4      5     Asha    TE   63.28   NaN
5      6   Ayesha    BE     NaN  20.0
6      7     Amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     Amol    TE   56.75  20.0
9      9     Amol    TE   56.75  20.0
10    10    Anmol    BE   78.66   NaN
11    11   Surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  Subhash    be   88.45  21.0
14    14   Sachin   NaN   59.33  21.0
15    15  Shalini    TE   63.45  20.0

In [8]:
df['class']=df['class'].str.upper()

In [13]:
df

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
9      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [9]:
df.columns=df.columns.str.strip()

In [10]:
df['marks'];

In [11]:
df. duplicated();

In [12]:
df.duplicated().sum()

np.int64(1)

In [14]:
df

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
9      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [15]:
# removing the null values

In [16]:
df.dropna()

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
9      9     Amol    TE  56.75  20.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
15    15  Shalini    TE  63.45  20.0

In [17]:
df['marks'].fillna(60)

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5     60.00
6     65.34
7     68.33
8     56.75
9     56.75
10    78.66
11    60.00
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64

In [ ]:
df.bfill(in