In [1]:
# array

In [2]:
import numpy as np

In [3]:
a = np.array([2,44.5,True,'aryan'])

In [4]:
a

array(['2', '44.5', 'True', 'aryan'], dtype='<U32')

# DataFrame

In [5]:
import pandas as pd

In [7]:
roll = pd.Series([1,2,3,4,5])
name = pd.Series(['Sia','Ravi','Geet','Ajeenkya','Avinash'])
marks = pd.Series([85,67,59,40,90])

In [10]:
df = pd.DataFrame({
    'id': roll,
    'name':name,
    'marks':marks

})

In [11]:
df

   id      name  marks
0   1       Sia     85
1   2      Ravi     67
2   3      Geet     59
3   4  Ajeenkya     40
4   5   Avinash     90

In [12]:
df.ndim

2

In [13]:
df.shape

(5, 3)

In [14]:
df.size

15

In [15]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [16]:
"""
URL: https://mitu.co.in/dataset

Download all datasets whose names start with 'student'.

Save the downloaded files in the current working directory (same folder as your Python file).

These files will be used to create and analyze DataFrames.
""";

In [20]:
pwd

'C:\\Users\\Lenovo'

In [22]:
df = pd.read_csv("student.csv")

In [23]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [24]:
df.shape

(10, 5)

In [25]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [26]:
# student1.csv

In [27]:
df = pd.read_csv("student1.csv")

In [28]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [30]:
col = ['roll','name','class','marks','age']

In [31]:
df = pd.read_csv('student1.csv',names = col)

In [32]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [33]:
# student3.tsv

In [38]:
df = pd.read_csv("student3.tsv")

In [39]:
df

  roll\tname\tclass\tmarks\tage
0        1\tanil\tTE\t56.77\t22
1        2\tamit\tTE\t59.77\t21
2      3\taniket\tBE\t76.88\t19
3     4\tajinkya\tTE\t69.66\t20
4        5\tasha\tTE\t63.28\t20
5      6\tayesha\tBE\t49.55\t20
6        7\tamar\tBE\t65.34\t19
7       8\tamita\tBE\t68.33\t23
8        9\tamol\tTE\t56.75\t20
9      10\tanmol\tBE\t78.66\t21

In [44]:
# another way 
df = pd.read_table("student3.tsv")

In [41]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [42]:
df = pd.read_csv("student3.tsv",sep = '\t')

In [43]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21