# Python Weekly Assignment 04

In [1]:
# Topics: Exception Handling · NumPy · Pandas Basics.

# Section A — Exception Handling

In [2]:
"""1. Write a function safe_divide(a, b) that divides two numbers and handles ZeroDivisionError and
TypeError separately, printing an appropriate message for each. Use a finally block to print
'Operation attempted.' regardless of the outcome. Test it with valid numbers, division by zero, and a
string input.""";

In [10]:
def safe_divide(a, b):
    try:
        result = a / b
        print("Result =", result)

    except ZeroDivisionError:
        print("Cannot divide by zero.")

    except TypeError:
        print("Invalid data type.")

    finally:
        print("Operation attempted.")

In [11]:
safe_divide(10, 2)

Result = 5.0
Operation attempted.

In [12]:
safe_divide(10, 0)

Cannot divide by zero.
Operation attempted.

In [13]:
safe_divide(10, "a")

Invalid data type.
Operation attempted.

In [14]:
"""2. Write a function validate_age(age) that raises a custom exception InvalidAgeError (a class you
define, inheriting from Exception) if age is negative or greater than 120. Catch this exception in a
calling block and print a user-friendly message. Test it with at least 3 different values.""";

In [21]:
class InvalidAgeError(Exception):
    pass

def validate_age(age):
    if age < 0 or age > 120:
        raise InvalidAgeError("Invalid Age")
    print("Valid Age =", age)

In [22]:
try:
    validate_age(25)
except InvalidAgeError as e:
    print(e)

Valid Age = 25

In [23]:
try:
    validate_age(-5)
except InvalidAgeError as e:
    print(e)

Invalid Age

In [24]:
try:
    validate_age(250)
except InvalidAgeError as e:
    print(e)

Invalid Age

In [26]:
"""3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list,
e.g. user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it. Handle the following in
a single try block using multiple except clauses:
a) ValueError if the input is not a number.
b) ZeroDivisionError if the input is zero.
c) A generic Exception as a catch-all for anything else.
Print the result if successful, otherwise print which error occurred.""";

In [33]:
user_inputs = ['10', 'abc', '0', '5']

for i in user_inputs:
    try:
        num = int(i)
        result = 100 / num
        print("Result =", result)

    except ValueError:
        print("ValueError occurred")

    except ZeroDivisionError:
        print("ZeroDivisionError occurred")

    except Exception:
        print("Some other error occurred")

Result = 10.0
ValueError occurred
ZeroDivisionError occurred
Result = 20.0

# Section B — NumPy

In [34]:
"""4. Create a 1D NumPy array of integers from 1 to 20. Perform the following:
a) Reshape it into a 4x5 2D array.
b) Print the sum of each row and each column.
c) Extract all elements greater than 10 using boolean indexing.
d) Replace all even numbers in the array with -1.""";

In [35]:
import numpy as np

In [38]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
# a)
a = arr.reshape(4,5)

print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

In [41]:
# b)
print("Row sum =", a.sum(axis=1))
print("Column sum =", a.sum(axis=0))

Row sum = [15 40 65 90]
Column sum = [34 38 42 46 50]

In [42]:
# c)
print(arr[arr > 10])

[11 12 13 14 15 16 17 18 19 20]

In [45]:
# d)
arr[arr % 2 == 0] = -1
print(arr)

[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]

In [46]:
"""5. Create two NumPy arrays A and B as shown below and perform:
A = np.array([[1, 2], [3, 4]]) B = np.array([[5, 6], [7, 8]])
a) Element-wise addition, subtraction, and multiplication.
b) Matrix multiplication using np.dot() or the @ operator.
c) Transpose of A.
d) The determinant and inverse of A using np.linalg.""";

In [47]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [56]:
#a)
print(A+B)
print(A-B)
print(A*B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]

In [57]:
# b)
print(np.dot(A,B))

[[19 22]
 [43 50]]

In [59]:
# c)
print(A.T)

[[1 3]
 [2 4]]

In [60]:
# d)
print("Determinant =", np.linalg.det(A))

print("Inverse =")
print(np.linalg.inv(A))

Determinant = -2.0000000000000004
Inverse =
[[-2.   1. ]
 [ 1.5 -0.5]]

In [61]:
"""6. Generate a NumPy array of 15 random integers between 1 and 100 using np.random.randint()
(set a seed of 42 for reproducibility). Then:
a) Find the mean, median, standard deviation, min, and max.
b) Sort the array in descending order.
c) Find the indices of the 3 largest values using np.argsort().
d) Normalize the array so all values lie between 0 and 1""";

In [62]:
np.random.seed(42)

arr = np.random.randint(1,101,15)

print(arr)

[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]

In [63]:
# np.random.seed() initializes the random number generator so that the same random numbers are generated every time the program is run.

In [67]:
print("Mean =", np.mean(arr))
print("Median =", np.median(arr))
print("Std =", np.std(arr))
print("Min =", np.min(arr))
print("Max =", np.max(arr))

Mean = 58.06666666666667
Median = 72.0
Std = 31.4843170836247
Min = 3
Max = 100

In [65]:
print(np.sort(arr)[::-1])

[100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]

In [66]:
print(np.argsort(arr)[-3:])

[10  1 11]

In [68]:
"""np.argsort() returns the indices that would sort the array. By taking the last three indices using [-3:],
we get the indices of the three largest values.""";

In [69]:
norm = (arr-arr.min())/(arr.max()-arr.min())

print(norm)

[0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]

# Section C — Pandas Basics

In [5]:
"""7. Create a Pandas DataFrame from the dictionary below and perform the following:
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], "Age": [23, 21,
25, 22, 24], "Department": ["AI", "Data Science", "AI", "Web Dev", "Data
Science"], "Score": [88, 92, 79, 95, 67], }
a) Display the first 3 rows and the data types of each column.
b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').
c) Sort the DataFrame by Score in descending order.
d) Filter rows where Department is 'AI'.""";

In [6]:
import pandas as pd

In [7]:
data = {
"Name":["Aarav","Priya","Karan","Meera","Sahil"],
"Age":[23,21,25,22,24],
"Department":["AI","Data Science","AI","Web Dev","Data Science"],
"Score":[88,92,79,95,67]
}

df = pd.DataFrame(data)

In [8]:
df

    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

In [9]:
# a)
print(df.head(3))

    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

In [10]:
print(df.dtypes)

Name          object
Age            int64
Department    object
Score          int64
dtype: object

In [11]:
# b)
df['Grade'] = 'C'

df.loc[df['Score'] >= 75, 'Grade'] = 'B'
df.loc[df['Score'] >= 90, 'Grade'] = 'A'

print(df)

    Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

In [12]:
# c)
print(df.sort_values("Score", ascending=False))

    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C

In [13]:
# d)
print(df[df["Department"]=="AI"])

    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B

In [14]:
"""8. Using the same DataFrame from Q7:
a) Group by Department and find the average Score for each.
b) Find the row with the highest Score using idxmax().
c) Rename the column Score to Marks.
d) Drop the Age column and display the resulting DataFrame""";

In [15]:
# a)
print(df.groupby("Department")["Score"].mean())

Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64

In [16]:
# b)
print(df.loc[df["Score"].idxmax()])

Name            Meera
Age                22
Department    Web Dev
Score              95
Grade               A
Name: 3, dtype: object

In [17]:
# c)
df.rename(columns={"Score":"Marks"}, inplace=True)

print(df)

    Name  Age    Department  Marks Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

In [18]:
# d)
df.drop("Age", axis=1, inplace=True)

print(df)

    Name    Department  Marks Grade
0  Aarav            AI     88     B
1  Priya  Data Science     92     A
2  Karan            AI     79     B
3  Meera       Web Dev     95     A
4  Sahil  Data Science     67     C

In [19]:
"""9. Create a DataFrame with some missing values as shown below and handle them:
import numpy as np data = { "Product": ["Pen", "Notebook", "Eraser",
"Sharpener", "Ruler"], "Price": [10, np.nan, 5, 8, np.nan], "Stock": [100, 50,
np.nan, 30, 20], }
a) Check the number of missing values in each column using isnull().sum().
b) Fill missing Price values with the column mean.
c) Drop rows where Stock is still missing.
d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index.""";

In [20]:
import numpy as np

data = {
"Product":["Pen","Notebook","Eraser","Sharpener","Ruler"],
"Price":[10,np.nan,5,8,np.nan],
"Stock":[100,50,np.nan,30,20]
}

df = pd.DataFrame(data)

In [21]:
df

     Product  Price  Stock
0        Pen   10.0  100.0
1   Notebook    NaN   50.0
2     Eraser    5.0    NaN
3  Sharpener    8.0   30.0
4      Ruler    NaN   20.0

In [22]:
# a)
print(df.isnull().sum())

Product    0
Price      2
Stock      1
dtype: int64

In [23]:
# b)
df["Price"] = df["Price"].fillna(df["Price"].mean())

print(df)

     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
2     Eraser   5.000000    NaN
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

In [24]:
# c)
df.dropna(subset=["Stock"], inplace=True)

print(df)

     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

In [25]:
# d)
df.to_csv("cleaned_products.csv", index=False)

In [26]:
"""10. Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:
a) Print its shape and column names.
b) Add a new column Total_Value as Price multiplied by Stock.
c) Use describe() to print summary statistics of the numeric columns.
d) Wrap the file reading step in a try-except block to handle the case where the file does not
exist (FileNotFoundError)""";

In [28]:
# a)
try:
    newdf = pd.read_csv("cleaned_products.csv")

    print(newdf.shape)

    print(newdf.columns)

except FileNotFoundError:
    print("File not found")

(4, 3)
Index(['Product', 'Price', 'Stock'], dtype='object')

In [29]:
# b)
newdf["Total_Value"] = newdf["Price"] * newdf["Stock"]

print(newdf)

     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333

In [30]:
# c)
newdf["Total_Value"] = newdf["Price"] * newdf["Stock"]

print(newdf)

     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333