# Data Cleaning

In [1]:
# student3.csv

In [2]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv('student3.csv')

In [24]:
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [25]:
df.shape

(16, 5)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    16 non-null     int64
 1   name    16 non-null     object
 2   class   15 non-null     object
 3   marks   14 non-null     float64
 4   age     14 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 772.0+ bytes

In [7]:
# fix structural errors

In [8]:
df['name']

0        anil
1        amit
2      aniket
3     ajinkya
4        asha
5      ayesha
6        amar
7       Amita
8        amol
9        amol
10      anmol
11     surbhi
12      Sujay
13    subhash
14     sachin
15    shalini
Name: name, dtype: object

In [28]:
df['name'] = df['name'].str.title()

In [29]:
df

    roll     name class  marks    age
0      1     Anil    TE   56.77  22.0
1      2     Amit    TE   59.77  21.0
2      3   Aniket    BE   76.88  19.0
3      4  Ajinkya    TE   69.66  20.0
4      5     Asha    TE   63.28   NaN
5      6   Ayesha    BE     NaN  20.0
6      7     Amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     Amol    TE   56.75  20.0
9      9     Amol    TE   56.75  20.0
10    10    Anmol    BE   78.66   NaN
11    11   Surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  Subhash    be   88.45  21.0
14    14   Sachin   NaN   59.33  21.0
15    15  Shalini    TE   63.45  20.0

In [30]:
df['class']

0      TE
1      TE
2      BE
3      TE
4      TE
5      BE
6      BE
7      be
8      TE
9      TE
10     BE
11     TE
12     TE
13     be
14    NaN
15     TE
Name: class, dtype: object

In [31]:
df['class'] = df['class'].str.upper()

In [32]:
df

    roll     name class  marks    age
0      1     Anil    TE   56.77  22.0
1      2     Amit    TE   59.77  21.0
2      3   Aniket    BE   76.88  19.0
3      4  Ajinkya    TE   69.66  20.0
4      5     Asha    TE   63.28   NaN
5      6   Ayesha    BE     NaN  20.0
6      7     Amar    BE   65.34  19.0
7      8    Amita    BE   68.33  23.0
8      9     Amol    TE   56.75  20.0
9      9     Amol    TE   56.75  20.0
10    10    Anmol    BE   78.66   NaN
11    11   Surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  Subhash    BE   88.45  21.0
14    14   Sachin   NaN   59.33  21.0
15    15  Shalini    TE   63.45  20.0

In [33]:
df['marks']

KeyError: 'marks'

In [34]:
df.columns

Index(['roll', 'name', 'class', 'marks ', 'age'], dtype='object')

In [35]:
df.columns = df.columns.str.strip()

In [37]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [38]:
df['marks']

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5       NaN
6     65.34
7     68.33
8     56.75
9     56.75
10    78.66
11      NaN
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64

In [39]:
# duplictae value

In [42]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
dtype: bool

In [43]:
df.duplicated().sum()

np.int64(1)

In [44]:
df.drop_duplicates()

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [45]:
df

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
9      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [46]:
df.drop_duplicates(inplace=True)

In [47]:
df

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [48]:
# missing values

In [49]:
df.count()

roll     15
name     15
class    14
marks    13
age      13
dtype: int64

In [53]:
df.isnull()

     roll   name  class  marks    age
0   False  False  False  False  False
1   False  False  False  False  False
2   False  False  False  False  False
3   False  False  False  False  False
4   False  False  False  False   True
5   False  False  False   True  False
6   False  False  False  False  False
7   False  False  False  False  False
8   False  False  False  False  False
10  False  False  False  False   True
11  False  False  False   True  False
12  False  False  False  False  False
13  False  False  False  False  False
14  False  False   True  False  False
15  False  False  False  False  False

In [54]:
df.isnull().sum()

roll     0
name     0
class    1
marks    2
age      2
dtype: int64

In [55]:
df.isnull().sum().sum()

np.int64(5)

In [56]:
# removing rows with null value

In [57]:
df.dropna()

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
15    15  Shalini    TE  63.45  20.0

In [58]:
# filling the missing values

In [59]:
df['marks'].fillna(45)

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5     45.00
6     65.34
7     68.33
8     56.75
10    78.66
11    45.00
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64

In [60]:
# fill with avg marks

In [62]:
df['marks'] = df['marks'].fillna(df['marks'].mean())

In [63]:
df['marks']

0     56.770000
1     59.770000
2     76.880000
3     69.660000
4     63.280000
5     67.753077
6     65.340000
7     68.330000
8     56.750000
10    78.660000
11    67.753077
12    74.120000
13    88.450000
14    59.330000
15    63.450000
Name: marks, dtype: float64

In [64]:
df['age'] = df['age'].fillna(df['age'].median())

In [65]:
df['age']

0     22.0
1     21.0
2     19.0
3     20.0
4     21.0
5     20.0
6     19.0
7     23.0
8     20.0
10    21.0
11    23.0
12    22.0
13    21.0
14    21.0
15    20.0
Name: age, dtype: float64

In [66]:
# fill class column value with mode

In [70]:
df['class'].fillna(df['class'].mode())

0      TE
1      TE
2      BE
3      TE
4      TE
5      BE
6      BE
7      BE
8      TE
10     BE
11     TE
12     TE
13     BE
14    NaN
15     TE
Name: class, dtype: object

In [72]:
df['class'].fillna(df['class'].mode()[0])

0     TE
1     TE
2     BE
3     TE
4     TE
5     BE
6     BE
7     BE
8     TE
10    BE
11    TE
12    TE
13    BE
14    TE
15    TE
Name: class, dtype: object

In [73]:
# mode()[0] because we want 0th index value

In [74]:
df

    roll     name class      marks   age
0      1     Anil    TE  56.770000  22.0
1      2     Amit    TE  59.770000  21.0
2      3   Aniket    BE  76.880000  19.0
3      4  Ajinkya    TE  69.660000  20.0
4      5     Asha    TE  63.280000  21.0
5      6   Ayesha    BE  67.753077  20.0
6      7     Amar    BE  65.340000  19.0
7      8    Amita    BE  68.330000  23.0
8      9     Amol    TE  56.750000  20.0
10    10    Anmol    BE  78.660000  21.0
11    11   Surbhi    TE  67.753077  23.0
12    12    Sujay    TE  74.120000  22.0
13    13  Subhash    BE  88.450000  21.0
14    14   Sachin   NaN  59.330000  21.0
15    15  Shalini    TE  63.450000  20.0

In [75]:
df.ffill()

    roll     name class      marks   age
0      1     Anil    TE  56.770000  22.0
1      2     Amit    TE  59.770000  21.0
2      3   Aniket    BE  76.880000  19.0
3      4  Ajinkya    TE  69.660000  20.0
4      5     Asha    TE  63.280000  21.0
5      6   Ayesha    BE  67.753077  20.0
6      7     Amar    BE  65.340000  19.0
7      8    Amita    BE  68.330000  23.0
8      9     Amol    TE  56.750000  20.0
10    10    Anmol    BE  78.660000  21.0
11    11   Surbhi    TE  67.753077  23.0
12    12    Sujay    TE  74.120000  22.0
13    13  Subhash    BE  88.450000  21.0
14    14   Sachin    BE  59.330000  21.0
15    15  Shalini    TE  63.450000  20.0

In [78]:
df.bfill(inplace = True)

In [80]:
df.isnull().sum()

roll     0
name     0
class    0
marks    0
age      0
dtype: int64